### ISSUE TITLE
Store global settings in user folder

### ISSUE THREAD

**Issue by amaiorano** [martinecker/rudebuild#10]
Currently, global settings for the plugin version (and RudeBuildConsole) is stored in "c:\Program Files (x86)\RudeBuild\RudeBuild.GlobalSettings.config", for e.g., while the VSIX version saves in the auto-generated extensions folder, like "c:\Users[username]\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\ndi3o2ac.0gs\RudeBuild.GlobalSettings.config" for e.g.

There are a few problems with this:
- The plugin version requires write access to "C:\Program Files (x86)\RudeBuild", which is not the default on Windows 10, even if you drop UAC to the lowest level. This actually causes the installation to fail if it's not run as administrator; also, you can't change the global settings from within Visual Studio (pre 2015) unless you run VS as admin.
- The fact that the settings are separate for the plugin and VSIX versions is confusing. For instance, we setup our global settings within VS 2015, but then use the RudeBuildConsole in Program Files in scripts; these two don't share the same global settings.

I think the best solution is to move the settings file to the user folder and have it shared across all versions (plugin, VSIX, RudeBuildConsole).

**Comment by martinecker** [comment]
Thanks for your pull request to fix this. Merged in commit https://github.com/martinecker/rudebuild/commit/9becf5675aa63d214c0579aafb2b751567f8ab6d
