### ISSUE TITLE
Modifying Global Settings requires focus change to register value change

### ISSUE THREAD

**Issue by amaiorano** [martinecker/rudebuild#11]
If you open the Global Settings dialog in VS and modify the "Max. Unity File Size (KBs)" value and hit ENTER without changing focus out of that edit box, the value doesn't get saved. You need to change focus (hit TAB, or click elsewhere) for the value to be read and updated.

**Comment by martinecker** [comment]
Fixed. See https://github.com/martinecker/rudebuild/commit/cc3f40b9abba64b09cc563984b192aea738a20f2
