### ISSUE TITLE
Make it possible to upgrade existing installation

### ISSUE THREAD

**Issue by amaiorano** [martinecker/rudebuild#9]
Currently, upgrading RudeBuild requires uninstalling the existing version, then installing a new one. This means you also lose your current global settings (in RudeBuild.GlobalSettings) and have to set that up again. It would be nice to support upgrading when the version is newer.

**Comment by martinecker** [comment]
Done. See https://github.com/martinecker/rudebuild/commit/9524a9c9ab965df7d91e3d9d23be91081df60cb0

**Comment by amaiorano** [comment]
Thanks, Martin! I believe I tried this locally, and although it did allow me to install another version, it also replaced the GlobalSettings file. However, perhaps that issue is best tackled as part of [issue 10](https://github.com/martinecker/rudebuild/issues/10)
